#!/usr/bin/python
#Check Password Complexity
import re
password_dir = "C:\\Users\\user\\Desktop\\passwords\\"

def read_pass():
    output_list = ''
    with open(password_dir + 'passwords.txt', 'r') as input_file:
        for line in input_file.read():
            output_list += line
    for item in output_list.split('\n'):
            print("Your password is: " + item)
            password_check(item)


def password_check(password):
#    '''
#    Verify the strength of 'password
#    Returns a dict indicating the wrong criteria
#    A password is considered strong if:
#        8 characters length or more
#        1 digit or more
#        1 symbol or more
#        1 uppercase letter or more
#        1 lowercase letter or more
#    ''''


    count = 0
# calculating the length
    if len(password) > 8:
        count += 1
    else:
        print("Not 8 characters long")

# searching for digits
    if re.search(r"[\d]", password):
        count += 1
    elif re.search(r"[\d]", password) is None:
        print("No digits")
# searching for uppercase
    if re.search(r"[A-Z]", password):
        count += 1
    elif re.search(r"[A-Z]", password) is None:
        print("No uppercase")
# searching for lowercase
    if re.search(r"[a-z]", password):
        count += 1
    elif re.search(r"[a-z]", password) is None:
        print("no lowercase")
# searching for symbols
    if re.search(r"[ !#$%&'()*+,-./[\\\]^_`{|}~"+r'"]', password):
        count+= 1
    if re.search(r"[ !#$%&'()*+,-./[\\\]^_`{|}~"+r'"]', password) is None:
        print("No symbols")
# overall result
    if count ==5:
        print("Your password meets complexity requirements!")
        print("-----------------------------------")
    elif count < 5:
        print("This password does NOT meet complexity requirements.")
        print("-----------------------------------")

read_pass()
